tools-station:
  default:
    languages:
      - nodejs22
    steps:
      - run: npm install
        path: ./
      - run: npm run build
        path: ./
      - run: mkdir -p .next/standalone/.next
        path: ./
      - run: cp -r .next/static .next/standalone/.next/ 2>/dev/null || true
        path: ./
      - run: cp bootstrap .next/standalone/
        path: ./